/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as CalendarDemoRouteImport } from './routes/calendar-demo'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HostRouteImport } from './routes/host'
import { Route as HostProfileRouteImport } from './routes/host-profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SocialRouteImport } from './routes/social'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDemoRoute = CalendarDemoRouteImport.update({
  id: '/calendar-demo',
  path: '/calendar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HostProfileRoute = HostProfileRouteImport.update({
  id: '/host-profile',
  path: '/host-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/become-host': typeof BecomeHostRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/discover': typeof DiscoverRoute
  '/host': typeof HostRoute
  '/host-profile': typeof HostProfileRoute
  '/messages': typeof MessagesRoute
  '/nearby': typeof NearbyRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/become-host': typeof BecomeHostRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/discover': typeof DiscoverRoute
  '/host': typeof HostRoute
  '/host-profile': typeof HostProfileRoute
  '/messages': typeof MessagesRoute
  '/nearby': typeof NearbyRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/become-host': typeof BecomeHostRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/discover': typeof DiscoverRoute
  '/host': typeof HostRoute
  '/host-profile': typeof HostProfileRoute
  '/messages': typeof MessagesRoute
  '/nearby': typeof NearbyRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/social': typeof SocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/become-host'
    | '/calendar-demo'
    | '/discover'
    | '/host'
    | '/host-profile'
    | '/messages'
    | '/nearby'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/become-host'
    | '/calendar-demo'
    | '/discover'
    | '/host'
    | '/host-profile'
    | '/messages'
    | '/nearby'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/become-host'
    | '/calendar-demo'
    | '/discover'
    | '/host'
    | '/host-profile'
    | '/messages'
    | '/nearby'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BecomeHostRoute: typeof BecomeHostRoute
  CalendarDemoRoute: typeof CalendarDemoRoute
  DiscoverRoute: typeof DiscoverRoute
  HostRoute: typeof HostRoute
  HostProfileRoute: typeof HostProfileRoute
  MessagesRoute: typeof MessagesRoute
  NearbyRoute: typeof NearbyRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-demo': {
      id: '/calendar-demo'
      path: '/calendar-demo'
      fullPath: '/calendar-demo'
      preLoaderRoute: typeof CalendarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-profile': {
      id: '/host-profile'
      path: '/host-profile'
      fullPath: '/host-profile'
      preLoaderRoute: typeof HostProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BecomeHostRoute: BecomeHostRoute,
  CalendarDemoRoute: CalendarDemoRoute,
  DiscoverRoute: DiscoverRoute,
  HostRoute: HostRoute,
  HostProfileRoute: HostProfileRoute,
  MessagesRoute: MessagesRoute,
  NearbyRoute: NearbyRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
