import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

const role = v.union(
  v.literal('member'),
  v.literal('friend_host'),
  v.literal('reviewer'),
  v.literal('admin'),
  // Accepted only until existing owner records are migrated to admin.
  v.literal('owner'),
)
const verificationStatus = v.union(v.literal('not_started'), v.literal('pending'), v.literal('approved'), v.literal('rejected'))
const personaStatus = v.union(
  v.literal('not_started'),
  v.literal('created'),
  v.literal('in_progress'),
  v.literal('processing'),
  v.literal('completed'),
  v.literal('failed'),
  v.literal('expired'),
  // Legacy values remain readable while existing records are reconciled.
  v.literal('pending'),
  v.literal('approved'),
  v.literal('rejected'),
)
const personaDecision = v.union(v.literal('unknown'), v.literal('passed'), v.literal('needs_review'), v.literal('declined'))
const verificationAdminStatus = v.union(
  v.literal('not_ready'),
  v.literal('pending'),
  v.literal('approved'),
  v.literal('rejected'),
  // Legacy records used this value before provider and admin state were separated.
  v.literal('not_started'),
)
const verificationSource = v.union(v.literal('persona'), v.literal('legacy_manual'))
const hostStatus = v.union(v.literal('draft'), v.literal('pending_review'), v.literal('approved'), v.literal('rejected'), v.literal('suspended'))
const bookingStatus = v.union(v.literal('draft'), v.literal('verification_required'), v.literal('pending_admin_review'), v.literal('request_sent'), v.literal('accepted'), v.literal('declined'), v.literal('cancelled'), v.literal('completed'), v.literal('review_window'), v.literal('closed'))
const mode = v.union(v.literal('online'), v.literal('in_person'), v.literal('both'))
const postMedia = v.object({
  storageId: v.id('_storage'),
  kind: v.union(v.literal('image'), v.literal('video')),
  contentType: v.string(),
  size: v.number(),
})

export default defineSchema({
  users: defineTable({
    clerkUserId: v.string(),
    displayName: v.string(),
    profileImageStorageId: v.optional(v.id('_storage')),
    profileImageUrl: v.optional(v.string()),
    bio: v.optional(v.string()),
    onboardingGoal: v.optional(v.union(v.literal('member'), v.literal('friend_host'))),
    onboardingCompletedAt: v.optional(v.number()),
    role,
    verificationStatus,
    verificationSource: v.optional(verificationSource),
    identityVerifiedAt: v.optional(v.number()),
    identityExpiresAt: v.optional(v.number()),
    suspended: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_clerk_user_id', ['clerkUserId']).index('by_role', ['role']),
  verificationRequests: defineTable({
    userId: v.id('users'),
    reason: v.union(v.literal('member'), v.literal('booking'), v.literal('host_application'), v.literal('reverification')),
    personaInquiryId: v.optional(v.string()),
    personaAccountId: v.optional(v.string()),
    personaTemplateId: v.optional(v.string()),
    personaEnvironmentId: v.optional(v.string()),
    personaStatus,
    personaDecision: v.optional(personaDecision),
    verificationSource: v.optional(verificationSource),
    adminStatus: verificationAdminStatus,
    isCurrent: v.optional(v.boolean()),
    attempt: v.optional(v.number()),
    providerCreatedAt: v.optional(v.number()),
    providerStartedAt: v.optional(v.number()),
    providerCompletedAt: v.optional(v.number()),
    providerLastEventAt: v.optional(v.number()),
    adminQueuedAt: v.optional(v.number()),
    reviewedAt: v.optional(v.number()),
    supersededAt: v.optional(v.number()),
    providerFailureCode: v.optional(v.string()),
    bookingId: v.optional(v.id('bookings')),
    hostProfileId: v.optional(v.id('hostProfiles')),
    reviewerUserId: v.optional(v.id('users')),
    reviewerNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_user', ['userId'])
    .index('by_user_reason', ['userId', 'reason'])
    .index('by_user_current', ['userId', 'isCurrent'])
    .index('by_persona_inquiry_id', ['personaInquiryId'])
    .index('by_admin_status', ['adminStatus'])
    .index('by_reason_admin_status', ['reason', 'adminStatus'])
    .index('by_booking', ['bookingId'])
    .index('by_host_profile', ['hostProfileId']),
  personaWebhookEvents: defineTable({
    eventId: v.string(),
    eventName: v.string(),
    inquiryId: v.optional(v.string()),
    providerCreatedAt: v.optional(v.number()),
    receivedAt: v.number(),
    processedAt: v.number(),
    outcome: v.union(v.literal('processed'), v.literal('duplicate'), v.literal('ignored')),
  }).index('by_event_id', ['eventId']).index('by_inquiry_id', ['inquiryId']),
  hostProfiles: defineTable({
    userId: v.id('users'),
    displayName: v.string(),
    intro: v.string(),
    city: v.string(),
    approximateArea: v.optional(v.string()),
    approximateLatitude: v.optional(v.number()),
    approximateLongitude: v.optional(v.number()),
    nearbyDiscoveryEnabled: v.optional(v.boolean()),
    strengths: v.array(v.string()),
    categories: v.array(v.string()),
    boundaries: v.array(v.string()),
    mode,
    status: hostStatus,
    applicationNote: v.optional(v.string()),
    reviewerUserId: v.optional(v.id('users')),
    reviewerNote: v.optional(v.string()),
    rating: v.number(),
    reviewCount: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_user', ['userId']).index('by_status', ['status']),
  bookings: defineTable({
    memberId: v.id('users'),
    hostProfileId: v.id('hostProfiles'),
    category: v.string(),
    mode: v.union(v.literal('online'), v.literal('in_person')),
    requestedAt: v.number(),
    durationMinutes: v.number(),
    notes: v.optional(v.string()),
    status: bookingStatus,
    verificationRequestId: v.optional(v.id('verificationRequests')),
    hostDecisionNote: v.optional(v.string()),
    cancelledByUserId: v.optional(v.id('users')),
    cancelledAt: v.optional(v.number()),
    cancellationReason: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_member', ['memberId']).index('by_host', ['hostProfileId']).index('by_status', ['status']),
  messages: defineTable({
    bookingId: v.id('bookings'),
    senderId: v.id('users'),
    body: v.string(),
    reportable: v.boolean(),
    createdAt: v.number(),
  }).index('by_booking', ['bookingId']),
  reviews: defineTable({
    bookingId: v.id('bookings'),
    reviewerId: v.id('users'),
    revieweeId: v.id('users'),
    hostProfileId: v.optional(v.id('hostProfiles')),
    rating: v.number(),
    body: v.optional(v.string()),
    hidden: v.optional(v.boolean()),
    moderatorUserId: v.optional(v.id('users')),
    moderatorNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  }).index('by_booking', ['bookingId']).index('by_booking_reviewer', ['bookingId', 'reviewerId']).index('by_host_profile', ['hostProfileId']).index('by_reviewee', ['revieweeId']),
  posts: defineTable({
    authorId: v.id('users'),
    body: v.string(),
    media: v.optional(v.array(postMedia)),
    experienceBookingId: v.optional(v.id('bookings')),
    reportable: v.boolean(),
    hidden: v.boolean(),
    deletedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_author', ['authorId']).index('by_author_hidden_created_at', ['authorId', 'hidden', 'createdAt']).index('by_created_at', ['createdAt']),
  postMediaUploads: defineTable({
    userId: v.id('users'),
    storageId: v.optional(v.id('_storage')),
    postId: v.optional(v.id('posts')),
    kind: v.optional(v.union(v.literal('image'), v.literal('video'))),
    contentType: v.optional(v.string()),
    size: v.optional(v.number()),
    createdAt: v.number(),
    registeredAt: v.optional(v.number()),
    discardedAt: v.optional(v.number()),
  }).index('by_user_created_at', ['userId', 'createdAt']).index('by_storage_id', ['storageId']).index('by_post', ['postId']),
  postComments: defineTable({
    postId: v.id('posts'),
    authorId: v.id('users'),
    body: v.string(),
    reportable: v.boolean(),
    hidden: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_post', ['postId']).index('by_author', ['authorId']),
  follows: defineTable({
    followerId: v.id('users'),
    followingId: v.id('users'),
    createdAt: v.number(),
  }).index('by_follower', ['followerId']).index('by_following', ['followingId']).index('by_pair', ['followerId', 'followingId']),
  savedPosts: defineTable({
    userId: v.id('users'),
    postId: v.id('posts'),
    createdAt: v.number(),
  }).index('by_user', ['userId']).index('by_post', ['postId']).index('by_pair', ['userId', 'postId']),
  postReactions: defineTable({
    userId: v.id('users'),
    postId: v.id('posts'),
    reaction: v.literal('like'),
    createdAt: v.number(),
  }).index('by_user', ['userId']).index('by_post', ['postId']).index('by_pair', ['userId', 'postId']),
  savedReviews: defineTable({
    userId: v.id('users'),
    reviewId: v.id('reviews'),
    createdAt: v.number(),
  }).index('by_user', ['userId']).index('by_review', ['reviewId']).index('by_pair', ['userId', 'reviewId']),
  savedProfiles: defineTable({
    userId: v.id('users'),
    hostProfileId: v.id('hostProfiles'),
    createdAt: v.number(),
  }).index('by_user', ['userId']).index('by_host_profile', ['hostProfileId']).index('by_pair', ['userId', 'hostProfileId']),
  reports: defineTable({
    reporterId: v.id('users'),
    targetType: v.union(v.literal('profile'), v.literal('booking'), v.literal('message'), v.literal('review'), v.literal('post'), v.literal('comment'), v.literal('user')),
    targetId: v.string(),
    reason: v.string(),
    status: v.union(v.literal('open'), v.literal('reviewing'), v.literal('resolved'), v.literal('dismissed')),
    reviewerUserId: v.optional(v.id('users')),
    reviewerNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index('by_status', ['status']).index('by_reporter', ['reporterId']),
  auditLogs: defineTable({
    actorUserId: v.optional(v.id('users')),
    action: v.string(),
    targetType: v.string(),
    targetId: v.optional(v.string()),
    before: v.optional(v.any()),
    after: v.optional(v.any()),
    note: v.optional(v.string()),
    createdAt: v.number(),
  }).index('by_created_at', ['createdAt']),
})
