/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VerificationSecretImport } from './routes/verification/$secret'
import { Route as ProfileUserIdImport } from './routes/profile/$userId'
import { Route as PostPostIdImport } from './routes/post/$postId'
import { Route as ChatsAccountIdImport } from './routes/chats/$accountId'
import { Route as PostCreatePostIndexImport } from './routes/post/create-post/index'
import { Route as PostUpdatePostPostIdImport } from './routes/post/update-post/$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VerificationSecretRoute = VerificationSecretImport.update({
  path: '/verification/$secret',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUserIdRoute = ProfileUserIdImport.update({
  path: '/profile/$userId',
  getParentRoute: () => rootRoute,
} as any)

const PostPostIdRoute = PostPostIdImport.update({
  path: '/post/$postId',
  getParentRoute: () => rootRoute,
} as any)

const ChatsAccountIdRoute = ChatsAccountIdImport.update({
  path: '/chats/$accountId',
  getParentRoute: () => rootRoute,
} as any)

const PostCreatePostIndexRoute = PostCreatePostIndexImport.update({
  path: '/post/create-post/',
  getParentRoute: () => rootRoute,
} as any)

const PostUpdatePostPostIdRoute = PostUpdatePostPostIdImport.update({
  path: '/post/update-post/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chats/$accountId': {
      id: '/chats/$accountId'
      path: '/chats/$accountId'
      fullPath: '/chats/$accountId'
      preLoaderRoute: typeof ChatsAccountIdImport
      parentRoute: typeof rootRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdImport
      parentRoute: typeof rootRoute
    }
    '/verification/$secret': {
      id: '/verification/$secret'
      path: '/verification/$secret'
      fullPath: '/verification/$secret'
      preLoaderRoute: typeof VerificationSecretImport
      parentRoute: typeof rootRoute
    }
    '/post/update-post/$postId': {
      id: '/post/update-post/$postId'
      path: '/post/update-post/$postId'
      fullPath: '/post/update-post/$postId'
      preLoaderRoute: typeof PostUpdatePostPostIdImport
      parentRoute: typeof rootRoute
    }
    '/post/create-post/': {
      id: '/post/create-post/'
      path: '/post/create-post'
      fullPath: '/post/create-post'
      preLoaderRoute: typeof PostCreatePostIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats/$accountId': typeof ChatsAccountIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/verification/$secret': typeof VerificationSecretRoute
  '/post/update-post/$postId': typeof PostUpdatePostPostIdRoute
  '/post/create-post': typeof PostCreatePostIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats/$accountId': typeof ChatsAccountIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/verification/$secret': typeof VerificationSecretRoute
  '/post/update-post/$postId': typeof PostUpdatePostPostIdRoute
  '/post/create-post': typeof PostCreatePostIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chats/$accountId': typeof ChatsAccountIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/verification/$secret': typeof VerificationSecretRoute
  '/post/update-post/$postId': typeof PostUpdatePostPostIdRoute
  '/post/create-post/': typeof PostCreatePostIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats/$accountId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/verification/$secret'
    | '/post/update-post/$postId'
    | '/post/create-post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats/$accountId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/verification/$secret'
    | '/post/update-post/$postId'
    | '/post/create-post'
  id:
    | '__root__'
    | '/'
    | '/chats/$accountId'
    | '/post/$postId'
    | '/profile/$userId'
    | '/verification/$secret'
    | '/post/update-post/$postId'
    | '/post/create-post/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsAccountIdRoute: typeof ChatsAccountIdRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  VerificationSecretRoute: typeof VerificationSecretRoute
  PostUpdatePostPostIdRoute: typeof PostUpdatePostPostIdRoute
  PostCreatePostIndexRoute: typeof PostCreatePostIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsAccountIdRoute: ChatsAccountIdRoute,
  PostPostIdRoute: PostPostIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  VerificationSecretRoute: VerificationSecretRoute,
  PostUpdatePostPostIdRoute: PostUpdatePostPostIdRoute,
  PostCreatePostIndexRoute: PostCreatePostIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats/$accountId",
        "/post/$postId",
        "/profile/$userId",
        "/verification/$secret",
        "/post/update-post/$postId",
        "/post/create-post/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chats/$accountId": {
      "filePath": "chats/$accountId.tsx"
    },
    "/post/$postId": {
      "filePath": "post/$postId.tsx"
    },
    "/profile/$userId": {
      "filePath": "profile/$userId.tsx"
    },
    "/verification/$secret": {
      "filePath": "verification/$secret.tsx"
    },
    "/post/update-post/$postId": {
      "filePath": "post/update-post/$postId.tsx"
    },
    "/post/create-post/": {
      "filePath": "post/create-post/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
