/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VerificationSecretImport } from './routes/verification/$secret'
import { Route as ProfileUserIdImport } from './routes/profile/$userId'
import { Route as ChatsAccountIdImport } from './routes/chats/$accountId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VerificationSecretRoute = VerificationSecretImport.update({
  path: '/verification/$secret',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUserIdRoute = ProfileUserIdImport.update({
  path: '/profile/$userId',
  getParentRoute: () => rootRoute,
} as any)

const ChatsAccountIdRoute = ChatsAccountIdImport.update({
  path: '/chats/$accountId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chats/$accountId': {
      id: '/chats/$accountId'
      path: '/chats/$accountId'
      fullPath: '/chats/$accountId'
      preLoaderRoute: typeof ChatsAccountIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdImport
      parentRoute: typeof rootRoute
    }
    '/verification/$secret': {
      id: '/verification/$secret'
      path: '/verification/$secret'
      fullPath: '/verification/$secret'
      preLoaderRoute: typeof VerificationSecretImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats/$accountId': typeof ChatsAccountIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/verification/$secret': typeof VerificationSecretRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats/$accountId': typeof ChatsAccountIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/verification/$secret': typeof VerificationSecretRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chats/$accountId': typeof ChatsAccountIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/verification/$secret': typeof VerificationSecretRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats/$accountId'
    | '/profile/$userId'
    | '/verification/$secret'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats/$accountId' | '/profile/$userId' | '/verification/$secret'
  id:
    | '__root__'
    | '/'
    | '/chats/$accountId'
    | '/profile/$userId'
    | '/verification/$secret'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsAccountIdRoute: typeof ChatsAccountIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  VerificationSecretRoute: typeof VerificationSecretRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsAccountIdRoute: ChatsAccountIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  VerificationSecretRoute: VerificationSecretRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats/$accountId",
        "/profile/$userId",
        "/verification/$secret"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chats/$accountId": {
      "filePath": "chats/$accountId.tsx"
    },
    "/profile/$userId": {
      "filePath": "profile/$userId.tsx"
    },
    "/verification/$secret": {
      "filePath": "verification/$secret.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
